### ISSUE TITLE
Merge Motorul

### ISSUE THREAD

**Issue by haloandrei** [ABC-practica-2024/BlackPearl#1]
Un hello world in care scriem cod pentru a invarti un motor de pe placi:

- [x] Arduino
- [x] ESP S3
- [x] ESP C6
- [x] Rasp Pi5

Taskul este marked ca si complet atunci cand avem un firmware care invarte motorul cu turatie reglabila pe fiecare model de placa.

**Comment by RacAndreea-916** [comment]
https://www.youtube.com/watch?v=oXJxyANeylc -circuit simplu cu LED folosind ESP32-C6-DevKitC-1

**Comment by RacAndreea-916** [comment]
https://www.youtube.com/shorts/yr2emnRzF-A -placa Arduino

**Comment by RacAndreea-916** [comment]
https://www.youtube.com/watch?v=n8A8BEAUaV0 -Raspberry Pi 5

**Comment by haloandrei** [comment]
Closing this as solve
