### ISSUE TITLE
Rotatie Barca

### ISSUE THREAD

**Issue by haloandrei** [ABC-practica-2024/BlackPearl#27]
Nu cred ca avem un senzor de rotatie. Poate cineva sa verifice accelerometrele daca au? Daca nu trebuie comandat

- [ ] Verifica placile de accelerometru
- [ ] ESP controller collects/saves rotational data

**Comment by cheresandreea** [comment]
nu avem shield ca sa conectam accelerometrul la controller

**Comment by cheresandreea** [comment]
nu are senzor de rotatie
