### ISSUE TITLE
Conectarea ESP la baterie

### ISSUE THREAD

**Issue by haloandrei** [ABC-practica-2024/BlackPearl#28]
Power an ESP to a battery

**Comment by cheresandreea** [comment]
We did it
![circuitESPBattery](https://github.com/user-attachments/assets/15ade8ac-62a4-4e97-9411-dea32712422a)

**Comment by haloandrei** [comment]
@912-Cseke-Stefan sa adaugati un fisier cu documentatie in repo te rog
