### ISSUE TITLE
Interfata cu harta pentru telecomanda

### ISSUE THREAD

**Issue by 912-Cseke-Stefan** [ABC-practica-2024/BlackPearl#56]
Realizeaza o interfata ce incorporeaza o harta de la Google Maps. Aceasta interfata va fi hostata pe Raspberry Pi, va comunica telecomenzii coordonatele la care sa trimita barca si va primi coordonatele curente ale barcii de la aceasta. 

A se studia modalitatile de a transmite programatic coordonatele catre acest API.

**Comment by Meka04** [comment]
Google API:  https://developers.google.com/maps/documentation/embed/embedding-map

**Comment by 912-Cseke-Stefan** [comment]
In mod alternativ, interfata frontend poate sa fie ea insasi un client MQTT si sa obtina astfel coordonatele
